#!/usr/bin/env bash

# This script takes a table with selected gene groups and re-formats all the information
# gathered about them for easier use. It will also re-run interproscan to generate
# outputs injson format to be imported into their website and generate graphical displays of the contigs.

# The input table requires the following columns:
# Region	Gene_Group	Type	GeneID	Annotation_Source
# PTC3_iM_Zhang_2024	C-Lectin__Gr1	R	LOC106059282	Bg_2024

# These indicate the region that is being considered, the gene group, type (indication if the gene is the reference taken for the group or an overlapping gene)
# Gene ID and annotation source. They will be used to retrieve information from the right place and label it properly.
# The script will not check if any of them are valid, so exercise caution.

# 1) Input table:
gene_input_table=/nfs5/IB/Blouin_Lab/users/javierc/ANALYSIS/Key_Region_Anotation/Interest_gene_reports/Gene_Model_Input.in

# 2) Work directory
work_directory=/nfs5/IB/Blouin_Lab/users/javierc/ANALYSIS/Key_Region_Anotation/Interest_gene_reports

# 3) TargetP work table (easy access to prot IDs)
targetP_tables=/nfs5/IB/Blouin_Lab/users/javierc/ANALYSIS/Key_Region_Anotation/Ref_Genes_Annotation/TargetP

# 4) Refined Target region folder (generated by the main script)
region_folder=/nfs5/IB/Blouin_Lab/users/javierc/ANALYSIS/Key_Region_Anotation/Definitive_Regions

# 5) Genome assembly input table with all the file locations for genome, proteins and annotations
genome_file=/nfs5/IB/Blouin_Lab/users/javierc/ANALYSIS/Key_Region_Anotation/Input_assemblies.in

# 6) Select References to check. This is not for the annotation sources, it is just the references that were finally used as independent genomes to analyze. The selection only matters to report gene locations on these references/
reference_assemblies_IDs=$(echo "Bg_2024 BS90_bu_et_al_qtl iM_Zhang_2024")

# 7) Interpro instalation folders (Singularity)
interpro_data=/nfs5/IB/Blouin_Lab/users/javierc/data/Interpro_local_data/interproscan-5.74-105.0/data
sif_image_path=/nfs5/IB/Blouin_Lab/users/javierc/data/Interpro_local_data

################################################################################
################################################################################

if [ ! -d $work_directory"/temp" ]
then
  mkdir $work_directory"/temp"
fi

count_gene=2
walker_gene=$(grep -c . $gene_input_table)
while [ $count_gene -le $walker_gene ]
do
  # Gather data
  regionID=$(sed -n $count_gene"p" $gene_input_table | awk -F "\t" '{print $1}')
  gene_group=$(sed -n $count_gene"p" $gene_input_table | awk -F "\t" '{print $2}')
  gene_type=$(sed -n $count_gene"p" $gene_input_table | awk -F "\t" '{print $3}')
  geneID=$(sed -n $count_gene"p" $gene_input_table | awk -F "\t" '{print $4}')

  annot_source=$(sed -n $count_gene"p" $gene_input_table | awk -F "\t" '{print $5}')
  search_geneID=$(echo $geneID | sed "s/^gene-//")

  echo $regionID": "$geneID" ("$annot_source")"

  protein_file=$(awk -F "\t" -v genomeID=$annot_source '{if ($1==genomeID) print $5}' $genome_file)

  if [ ! -d $work_directory"/"$regionID ]
  then
    mkdir $work_directory"/"$regionID
  fi

  if [ ! -f $work_directory"/"$regionID"/Location_signals_and_tmhmm.txt" ]
  then
    echo "Gene_Group GeneID Type SignalP6 TargetP TMHMM Annot_Source"  | tr " " "\t" >> $work_directory"/"$regionID"/Location_signals_and_tmhmm.txt"
  fi

  if [ ! -d $work_directory"/"$regionID"/"$gene_group ]
  then
    mkdir $work_directory"/"$regionID"/"$gene_group
    mkdir $work_directory"/"$regionID"/"$gene_group"/Sequences_References"
    mkdir $work_directory"/"$regionID"/"$gene_group"/Interpro_Json"
  fi

  if [ ! -f $work_directory"/"$regionID"/"$gene_group"/Location_signal_information.txt" ]
  then
    echo "GeneID Type ProtID SignalP TargetP" | tr " " "\t" > $work_directory"/"$regionID"/"$gene_group"/Location_signal_information.txt"
    echo "GenID Reference Chr Start End Strand" > $work_directory"/"$regionID"/"$gene_group"/Gene_Coords_on_Ref.txt"
  fi

  replace_protein_id=$(echo ">"$gene_group"__"$geneID"_"$gene_type"_")

  # 1) Retrieve sequence data
  check_prot_data=$(awk -F "\t" -v gene=$search_geneID '{if ($1==gene) print}' $targetP_tables"/"$annot_source"_TargetP.txt" | grep -c .)

  if [ $check_prot_data -gt 0 ]
  then
    awk -F "\t" -v gene=$search_geneID '{if ($1==gene) print $2}' $targetP_tables"/"$annot_source"_TargetP.txt" >> $work_directory"/"$regionID"/"$gene_group"/Sequences_References/temp_file.tmp"
    seqkit grep -f $work_directory"/"$regionID"/"$gene_group"/Sequences_References/temp_file.tmp" $protein_file | seqkit seq -i | sed "s/>/$replace_protein_id/" >> $work_directory"/"$regionID"/"$gene_group"/Sequences_References/"$gene_group"_seq.aa"

    proteins=$(cat $work_directory"/"$regionID"/"$gene_group"/Sequences_References/temp_file.tmp" | sort -u)

    gene_signalp=$(awk -F "\t" -v genID=$search_geneID '{if ($1==genID) print $3}' $region_folder"/"$regionID"/Genes_on_Regions/Annotation/Location_Signals/"$annot_source"_SignalP6.txt" | grep -c "SP" | awk '{if ($1>0) print "X"; else print "."}')
    gene_targetp=$(awk -F "\t" -v genID=$search_geneID '{if ($1==genID) print $3}' $region_folder"/"$regionID"/Genes_on_Regions/Annotation/Location_Signals/"$annot_source"_TargetP.txt" | grep -c "mTP" | awk '{if ($1>0) print "X"; else print "."}')
    gene_tmhmm=$(awk -F "\t" -v genID=$search_geneID '{if ($1==genID && $3>0) print }' $region_folder"/"$regionID"/Genes_on_Regions/Annotation/Location_Signals/"$annot_source"_tmhmm.txt" | grep -c . | awk '{if ($1>0) print "X"; else print "."}')

    echo $gene_group" "$geneID" "$gene_type" "$gene_signalp" "$gene_targetp" "$gene_tmhmm" "$annot_source | tr " " "\t" >> $work_directory"/"$regionID"/Location_signals_and_tmhmm.txt"

    for protid in $proteins
    do
      signalp=$(awk -F "\t" -v protID=$protid '{if ($2==protID) print $3}' $region_folder"/"$regionID"/Genes_on_Regions/Annotation/Location_Signals/"$annot_source"_SignalP6.txt")
      targetp=$(awk -F "\t" -v protID=$protid '{if ($2==protID) print $3}' $region_folder"/"$regionID"/Genes_on_Regions/Annotation/Location_Signals/"$annot_source"_TargetP.txt")
      echo $geneID" "$gene_type" "$protid" "$signalp" "$targetp | tr " " "\t" >> $work_directory"/"$regionID"/"$gene_group"/Location_signal_information.txt"
    done
    rm -f $work_directory"/"$regionID"/"$gene_group"/Sequences_References/temp_file.tmp"
  else
    echo $gene_group" "$geneID" "$gene_type" NA NA NA "$annot_source | tr " " "\t" >> $work_directory"/"$regionID"/Location_signals_and_tmhmm.txt"
    echo $gene_group" "$geneID" "$gene_type" NA NA NA "$annot_source | tr " " "\t" >> $work_directory"/"$regionID"/"$gene_group"/Location_signal_information.txt"
  fi

  # 2) Assembly recovery information
  all_assemblies=$(ls $region_folder"/"$regionID"/Genes_on_Regions/Source_"$annot_source"_transfered_to_"*"_info.txt" | sed "s/.*_transfered_to_//" | sed "s/_info.txt//")
  if [ ! -f $work_directory"/"$regionID"/Assembly_identity_conservation.txt" ]
  then
    echo "Gene_Group GeneID Type "$all_assemblies | tr " " "\t" >> $work_directory"/"$regionID"/Assembly_identity_conservation.txt"
    echo "Gene_Group GeneID Type "$all_assemblies | tr " " "\t" >> $work_directory"/"$regionID"/Assembly_coverage_conservation.txt"
    echo "Gene_Group GeneID Type "$all_assemblies | tr " " "\t" >> $work_directory"/"$regionID"/Assembly_orf_conservation.txt"
  fi

  regestry_ident=$(echo $gene_group" "$geneID" "$gene_type)
  regestry_coverage=$(echo $gene_group" "$geneID" "$gene_type)
  regestry_orf=$(echo $gene_group" "$geneID" "$gene_type)

  for assemblyID in $all_assemblies
  do
    check_information=$(grep -P $geneID"\t" $region_folder"/"$regionID"/Genes_on_Regions/Source_"$annot_source"_transfered_to_"$assemblyID"_info.txt" | grep -c .)

    if [ $check_information -eq 0 ]
    then
      regestry_ident=$(echo $regestry_ident" NA")
      regestry_coverage=$(echo $regestry_coverage" NA")
      regestry_orf=$(echo $regestry_orf" NA")
    else
      gene_ident=$(grep -P $geneID"\t" $region_folder"/"$regionID"/Genes_on_Regions/Source_"$annot_source"_transfered_to_"$assemblyID"_info.txt" | awk -F "\t" '{print $9}')
      gene_coverage=$(grep -P $geneID"\t" $region_folder"/"$regionID"/Genes_on_Regions/Source_"$annot_source"_transfered_to_"$assemblyID"_info.txt" | awk -F "\t" '{print $10}')
      gene_orf=$(grep -P $geneID"\t" $region_folder"/"$regionID"/Genes_on_Regions/Source_"$annot_source"_transfered_to_"$assemblyID"_info.txt" | awk -F "\t" '{print $7}')

      regestry_ident=$(echo $regestry_ident" "$gene_ident)
      regestry_coverage=$(echo $regestry_coverage" "$gene_coverage)
      regestry_orf=$(echo $regestry_orf" "$gene_orf)
    fi
  done
  echo $regestry_ident | tr " " "\t" >> $work_directory"/"$regionID"/Assembly_identity_conservation.txt"
  echo $regestry_coverage | tr " " "\t" >> $work_directory"/"$regionID"/Assembly_coverage_conservation.txt"
  echo $regestry_orf | tr " " "\t" >> $work_directory"/"$regionID"/Assembly_orf_conservation.txt"

  # 3) Location of the genes on each reference
  for refID in $reference_assemblies_IDs
  do
    gene_coords=$(grep "ID="$geneID";" $region_folder"/"$regionID"/Genes_on_Regions/Annotation_tracks/"$refID"/All_genes_from_"$annot_source".gff" | awk -F "\t" '{print $1" "$4" "$5" "$7}')
    check_data=$(echo $gene_coords | grep -c .)

    if [ $check_data -gt 0 ]
    then
      echo $geneID" "$refID" "$gene_coords | tr " " "\t" >> $work_directory"/"$regionID"/"$gene_group"/Gene_Coords_on_Ref.txt"
    else
      echo $geneID" "$refID" NA NA NA NA" | tr " " "\t" >> $work_directory"/"$regionID"/"$gene_group"/Gene_Coords_on_Ref.txt"
    fi
  done

  # 4) original annotation info
  if [ ! -f  $work_directory"/"$regionID"/Original_Anottation_info.txt" ]
  then
    echo "Gene_Group GeneID Type Original_Description" | tr " " "\t" >> $work_directory"/"$regionID"/Original_Anottation_info.txt"
  fi
  gene_information=$(grep -F $geneID $region_folder"/"$regionID"/Genes_on_Regions/Source_"$annot_source"_transfered_to_"*"_info.txt" | awk -F "\t" '{print $12}' | sort -u)
  echo $gene_group"_oooo_"$geneID"_oooo_"$gene_type"_oooo_"$gene_information | sed "s/_oooo_/\t/g" >> $work_directory"/"$regionID"/Original_Anottation_info.txt"

  count_gene=$(($count_gene + 1))
done

# 5) Submission to SLURM for protein definition
if [ -f $work_directory"/Cluster_submision_interpro.sh" ]
then
  rm -f $work_directory"/Cluster_submision_interpro.sh"
fi

all_gene_groups=$(sed 1d $gene_input_table | awk -F "\t" '{print $1"__ooo__"$2}' | sort -u)
for gene_group in $all_gene_groups
do
  reg=$(echo $gene_group | awk -F "__ooo__" '{print $1}')
  gm=$(echo $gene_group | awk -F "__ooo__" '{print $2}')

  if [ -f $work_directory"/"$reg"/"$gm"/Sequences_References/"$gm"_seq.aa" ]
  then
    echo "singularity exec -B "$interpro_data":/opt/interproscan/data -B "$work_directory"/"$reg"/"$gm"/Sequences_References:/input -B "$work_directory"/temp:/temp -B "$work_directory"/"$gene_group"/Interpro_Json:/output "$sif_image_path"/interproscan_latest.sif /opt/interproscan/interproscan.sh --input /input/"$gm"_seq.aa --disable-precalc -f JSON -dra --output-dir /output --tempdir /temp --cpu "'$NPROCS' >> $work_directory"/Cluster_submision_interpro.sh"
    cat $work_directory"/"$reg"/"$gm"/Sequences_References/"$gm"_seq.aa" >> $work_directory"/"$reg"/Proteins_For_KEGG.aa"
  fi
done
